from unittest import TestCase, main
from tasks.task_20_bast_shoe import BastShoe


class TestBastShoe(TestCase):

    def test_bast_shoe1(self):
        self.assertEqual(BastShoe("1 Привет"), "Привет")
        self.assertEqual(BastShoe("4"), "")
        self.assertEqual(BastShoe("5"), "Привет")
        self.assertEqual(BastShoe("1 , Мир!"), "Привет, Мир!")
        self.assertEqual(BastShoe("1 ++"), "Привет, Мир!++")
        self.assertEqual(BastShoe("2 2"), "Привет, Мир!")
        self.assertEqual(BastShoe("4"), "Привет, Мир!++")
        self.assertEqual(BastShoe("4"), "Привет, Мир!")
        self.assertEqual(BastShoe("1 *"), "Привет, Мир!*")
        self.assertEqual(BastShoe("4"), "Привет, Мир!")
        self.assertEqual(BastShoe("4"), "Привет, Мир!")
        self.assertEqual(BastShoe("4"), "Привет, Мир!")
        self.assertEqual(BastShoe("3 6"), ",")
        self.assertEqual(BastShoe("2 100"), "")
        self.assertEqual(BastShoe("1 Привет"), "Привет")
        self.assertEqual(BastShoe("1 , Мир!"), "Привет, Мир!")
        self.assertEqual(BastShoe("1 ++"), "Привет, Мир!++")
        self.assertEqual(BastShoe("4"), "Привет, Мир!")
        self.assertEqual(BastShoe("4"), "Привет")
        self.assertEqual(BastShoe("5"), "Привет, Мир!")
        self.assertEqual(BastShoe("4"), "Привет")
        self.assertEqual(BastShoe("5"), "Привет, Мир!")
        self.assertEqual(BastShoe("5"), "Привет, Мир!++")
        self.assertEqual(BastShoe("5"), "Привет, Мир!++")
        self.assertEqual(BastShoe("5"), "Привет, Мир!++")
        self.assertEqual(BastShoe("4"), "Привет, Мир!")
        self.assertEqual(BastShoe("4"), "Привет")
        self.assertEqual(BastShoe("2 2"), "Прив")
        self.assertEqual(BastShoe("4"), "Привет")
        self.assertEqual(BastShoe("5"), "Прив")
        self.assertEqual(BastShoe("5"), "Прив")
        self.assertEqual(BastShoe("5"), "Прив")
        self.assertEqual(BastShoe("3 -1"), "")
        self.assertEqual(BastShoe("3 0"), "П")
        self.assertEqual(BastShoe("3 3"), "в")
        self.assertEqual(BastShoe("3 4"), "")

    def test_bast_shoe2(self):
        print(BastShoe("1 Привет"), "Привет")
        print(BastShoe("1 , Мир!"), "Привет, Мир!")
        print(BastShoe("4"), "Привет")
        print(BastShoe("1 ++"), "Привет++")
        print(BastShoe("4"), "Привет")
        print(BastShoe("4"), "")
        print(BastShoe("1 ++"), "++")
        print(BastShoe("2 2"), "")

    def test_bast_shoe3(self):
        print(BastShoe("1 Привет"), "Привет")
        print(BastShoe("1 , Мир!"), "Привет, Мир!")
        print(BastShoe("4"), "Привет")
        print(BastShoe("1 ++"), "Привет++")
        print(BastShoe("4"), "Привет")
        print(BastShoe("1 ++"), "Привет++")
        print(BastShoe("4"), "Привет")
        print(BastShoe("1 ++"), "Привет++")
        print(BastShoe("4"), "Привет")
        print(BastShoe("1 ++"), "Привет++")
        print(BastShoe("4"), "Привет")
        print(BastShoe("1 ++"), "Привет++")
        print(BastShoe("4"), "Привет")

    def test_bast_shoe4(self):
        print(BastShoe("1 Привет"), "Привет")
        print(BastShoe("1 , Мир!"), "Привет, Мир!")
        print(BastShoe("1 ++"), "Привет, Мир!++")
        print(BastShoe("4"), "Привет, Мир!")
        print(BastShoe("4"), "Привет")
        print(BastShoe("1 , Мир!"), "Привет, Мир!")
        print(BastShoe("1 ++"), "Привет, Мир!++")
        print(BastShoe("4"), "Привет, Мир!")
        print(BastShoe("4"), "Привет")
        print(BastShoe("1 , Мир!"), "Привет, Мир!")
        print(BastShoe("1 ++"), "Привет, Мир!++")
        print(BastShoe("4"), "Привет, Мир!")
        print(BastShoe("4"), "Привет")
        print(BastShoe("1 , Мир!"), "Привет, Мир!")
        print(BastShoe("1 ++"), "Привет, Мир!++")


# print(BastShoe("1 Привет"))
# print(BastShoe("4"))
# print(BastShoe("5"))
# print(BastShoe("1 , Мир!"))
# print(BastShoe("1 ++"))
# print(BastShoe("2 2"))
# print(BastShoe("4"))
# print(BastShoe("4"))
# print(BastShoe("1 *"))
# print(BastShoe("4"))
# print(BastShoe("4"))
# print(BastShoe("4"))
# print(BastShoe("3 6"))
# print(BastShoe("2 100"))
# print(BastShoe("1 Привет"))
# print(BastShoe("1 , Мир!"))
# print(BastShoe("1 ++"))
# print(BastShoe("4"))
# print(BastShoe("4"))
# print(BastShoe("5"))
# print(BastShoe("4"))
# print(BastShoe("5"))
# print(BastShoe("5"))
# print(BastShoe("5"))
# print(BastShoe("5"))
# print(BastShoe("4"))
# print(BastShoe("4"))
# print(BastShoe("2 2"))
# print(BastShoe("4"))
# print(BastShoe("5"))
# print(BastShoe("5"))
# print(BastShoe("5"))
# print(BastShoe("3 -1"))
# print(BastShoe("3 0"))
# print(BastShoe("3 3"))
# print(BastShoe("3 4"))

if __name__ == '__main__':
    main()
